name: Deploy to Azure Spring Apps using passwordless connections (Vets Service)

on:
  push:
    branches:
      - Azure
    paths:
      - 'spring-petclinic-vets-service/**'
  workflow_dispatch:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      SPRING_APPS_SERVICE_NAME:
        required: true
      RESOURCE_GROUP:
        required: true

permissions:
  id-token: write
  contents: read

env:
  AZCLI_VER: 2.48.1
  # ==== APPS ====:
  VETS_SERVICE: vets-service
  # ==== TARGETS ====:
  VETS_SERVICE_TGT: spring-petclinic-vets-service

jobs:
  Deploy_Vets_Service:
    runs-on: ubuntu-latest
    steps:
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Deploy ${{ env.VETS_SERVICE }}
      uses: azure/CLI@v1
      with:
        azcliversion: ${{ env.AZCLI_VER }}
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az spring app deploy \
                  -g ${{ secrets.RESOURCE_GROUP }} \
                  --service ${{ secrets.SPRING_APPS_SERVICE_NAME }} \
                  -n ${{ env.VETS_SERVICE }} \
                  --source-path ${{ github.workspace }} \
                  --jvm-options="-XX:+UseG1GC -XX:+UseStringDeduplication -XX:InitialRAMPercentage=50.0 -XX:MinRAMPercentage=66.6 -XX:MaxRAMPercentage=66.6 -XX:ActiveProcessorCount=1" \
                  --env SPRING_PROFILES_ACTIVE=passwordless BP_JVM_VERSION=17 \
                  --target-module ${{ env.VETS_SERVICE_TGT }}
